### ISSUE TITLE
.wherePredicate() does not accept block predicates

### ISSUE THREAD

**Issue by callumboddy** [shaps80/Stack#2]
NSInvalidArgumentException', reason: 'Unknown predicate type for predicate: BLOCKPREDICATE(0x10b3656e0)'

**Comment by shaps80** [comment]
It does but you can't define it syntactically inside the parentheses.
Declare your predicate first, then pass it in like so.

``` objc
NSPredicate *predicate = [NSPredicate predicateWithBlock...];
stack.query(Object.class).wherePredicate(predicate);
```
